version = 0.1
[default.deploy.parameters]
stack_name = "shauploader"
resolve_s3 = true
s3_prefix = "shauploader"
region = "*"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []